// source: fourtyk.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.se.torrentkatten.fourtyk.api.GameDTO', null, global);
goog.exportSymbol('proto.se.torrentkatten.fourtyk.api.GameHandle', null, global);
goog.exportSymbol('proto.se.torrentkatten.fourtyk.api.GameResultDTO', null, global);
goog.exportSymbol('proto.se.torrentkatten.fourtyk.api.PlayerDTO', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.se.torrentkatten.fourtyk.api.PlayerDTO = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.se.torrentkatten.fourtyk.api.PlayerDTO, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.se.torrentkatten.fourtyk.api.PlayerDTO.displayName = 'proto.se.torrentkatten.fourtyk.api.PlayerDTO';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.se.torrentkatten.fourtyk.api.GameDTO = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.se.torrentkatten.fourtyk.api.GameDTO, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.se.torrentkatten.fourtyk.api.GameDTO.displayName = 'proto.se.torrentkatten.fourtyk.api.GameDTO';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.se.torrentkatten.fourtyk.api.GameHandle = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.se.torrentkatten.fourtyk.api.GameHandle, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.se.torrentkatten.fourtyk.api.GameHandle.displayName = 'proto.se.torrentkatten.fourtyk.api.GameHandle';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.se.torrentkatten.fourtyk.api.GameResultDTO = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.se.torrentkatten.fourtyk.api.GameResultDTO, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.se.torrentkatten.fourtyk.api.GameResultDTO.displayName = 'proto.se.torrentkatten.fourtyk.api.GameResultDTO';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.se.torrentkatten.fourtyk.api.PlayerDTO.prototype.toObject = function(opt_includeInstance) {
  return proto.se.torrentkatten.fourtyk.api.PlayerDTO.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.se.torrentkatten.fourtyk.api.PlayerDTO} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.se.torrentkatten.fourtyk.api.PlayerDTO.toObject = function(includeInstance, msg) {
  var f, obj = {
    faction: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.se.torrentkatten.fourtyk.api.PlayerDTO}
 */
proto.se.torrentkatten.fourtyk.api.PlayerDTO.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.se.torrentkatten.fourtyk.api.PlayerDTO;
  return proto.se.torrentkatten.fourtyk.api.PlayerDTO.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.se.torrentkatten.fourtyk.api.PlayerDTO} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.se.torrentkatten.fourtyk.api.PlayerDTO}
 */
proto.se.torrentkatten.fourtyk.api.PlayerDTO.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFaction(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.se.torrentkatten.fourtyk.api.PlayerDTO.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.se.torrentkatten.fourtyk.api.PlayerDTO.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.se.torrentkatten.fourtyk.api.PlayerDTO} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.se.torrentkatten.fourtyk.api.PlayerDTO.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFaction();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string faction = 1;
 * @return {string}
 */
proto.se.torrentkatten.fourtyk.api.PlayerDTO.prototype.getFaction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.se.torrentkatten.fourtyk.api.PlayerDTO} returns this
 */
proto.se.torrentkatten.fourtyk.api.PlayerDTO.prototype.setFaction = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.se.torrentkatten.fourtyk.api.GameDTO.prototype.toObject = function(opt_includeInstance) {
  return proto.se.torrentkatten.fourtyk.api.GameDTO.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.se.torrentkatten.fourtyk.api.GameDTO} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.se.torrentkatten.fourtyk.api.GameDTO.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    attacker: (f = msg.getAttacker()) && proto.se.torrentkatten.fourtyk.api.PlayerDTO.toObject(includeInstance, f),
    defender: (f = msg.getDefender()) && proto.se.torrentkatten.fourtyk.api.PlayerDTO.toObject(includeInstance, f),
    result: (f = msg.getResult()) && proto.se.torrentkatten.fourtyk.api.GameResultDTO.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.se.torrentkatten.fourtyk.api.GameDTO}
 */
proto.se.torrentkatten.fourtyk.api.GameDTO.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.se.torrentkatten.fourtyk.api.GameDTO;
  return proto.se.torrentkatten.fourtyk.api.GameDTO.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.se.torrentkatten.fourtyk.api.GameDTO} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.se.torrentkatten.fourtyk.api.GameDTO}
 */
proto.se.torrentkatten.fourtyk.api.GameDTO.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = new proto.se.torrentkatten.fourtyk.api.PlayerDTO;
      reader.readMessage(value,proto.se.torrentkatten.fourtyk.api.PlayerDTO.deserializeBinaryFromReader);
      msg.setAttacker(value);
      break;
    case 4:
      var value = new proto.se.torrentkatten.fourtyk.api.PlayerDTO;
      reader.readMessage(value,proto.se.torrentkatten.fourtyk.api.PlayerDTO.deserializeBinaryFromReader);
      msg.setDefender(value);
      break;
    case 5:
      var value = new proto.se.torrentkatten.fourtyk.api.GameResultDTO;
      reader.readMessage(value,proto.se.torrentkatten.fourtyk.api.GameResultDTO.deserializeBinaryFromReader);
      msg.setResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.se.torrentkatten.fourtyk.api.GameDTO.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.se.torrentkatten.fourtyk.api.GameDTO.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.se.torrentkatten.fourtyk.api.GameDTO} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.se.torrentkatten.fourtyk.api.GameDTO.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAttacker();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.se.torrentkatten.fourtyk.api.PlayerDTO.serializeBinaryToWriter
    );
  }
  f = message.getDefender();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.se.torrentkatten.fourtyk.api.PlayerDTO.serializeBinaryToWriter
    );
  }
  f = message.getResult();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.se.torrentkatten.fourtyk.api.GameResultDTO.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.se.torrentkatten.fourtyk.api.GameDTO.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.se.torrentkatten.fourtyk.api.GameDTO} returns this
 */
proto.se.torrentkatten.fourtyk.api.GameDTO.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional PlayerDTO attacker = 3;
 * @return {?proto.se.torrentkatten.fourtyk.api.PlayerDTO}
 */
proto.se.torrentkatten.fourtyk.api.GameDTO.prototype.getAttacker = function() {
  return /** @type{?proto.se.torrentkatten.fourtyk.api.PlayerDTO} */ (
    jspb.Message.getWrapperField(this, proto.se.torrentkatten.fourtyk.api.PlayerDTO, 3));
};


/**
 * @param {?proto.se.torrentkatten.fourtyk.api.PlayerDTO|undefined} value
 * @return {!proto.se.torrentkatten.fourtyk.api.GameDTO} returns this
*/
proto.se.torrentkatten.fourtyk.api.GameDTO.prototype.setAttacker = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.se.torrentkatten.fourtyk.api.GameDTO} returns this
 */
proto.se.torrentkatten.fourtyk.api.GameDTO.prototype.clearAttacker = function() {
  return this.setAttacker(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.se.torrentkatten.fourtyk.api.GameDTO.prototype.hasAttacker = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional PlayerDTO defender = 4;
 * @return {?proto.se.torrentkatten.fourtyk.api.PlayerDTO}
 */
proto.se.torrentkatten.fourtyk.api.GameDTO.prototype.getDefender = function() {
  return /** @type{?proto.se.torrentkatten.fourtyk.api.PlayerDTO} */ (
    jspb.Message.getWrapperField(this, proto.se.torrentkatten.fourtyk.api.PlayerDTO, 4));
};


/**
 * @param {?proto.se.torrentkatten.fourtyk.api.PlayerDTO|undefined} value
 * @return {!proto.se.torrentkatten.fourtyk.api.GameDTO} returns this
*/
proto.se.torrentkatten.fourtyk.api.GameDTO.prototype.setDefender = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.se.torrentkatten.fourtyk.api.GameDTO} returns this
 */
proto.se.torrentkatten.fourtyk.api.GameDTO.prototype.clearDefender = function() {
  return this.setDefender(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.se.torrentkatten.fourtyk.api.GameDTO.prototype.hasDefender = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional GameResultDTO result = 5;
 * @return {?proto.se.torrentkatten.fourtyk.api.GameResultDTO}
 */
proto.se.torrentkatten.fourtyk.api.GameDTO.prototype.getResult = function() {
  return /** @type{?proto.se.torrentkatten.fourtyk.api.GameResultDTO} */ (
    jspb.Message.getWrapperField(this, proto.se.torrentkatten.fourtyk.api.GameResultDTO, 5));
};


/**
 * @param {?proto.se.torrentkatten.fourtyk.api.GameResultDTO|undefined} value
 * @return {!proto.se.torrentkatten.fourtyk.api.GameDTO} returns this
*/
proto.se.torrentkatten.fourtyk.api.GameDTO.prototype.setResult = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.se.torrentkatten.fourtyk.api.GameDTO} returns this
 */
proto.se.torrentkatten.fourtyk.api.GameDTO.prototype.clearResult = function() {
  return this.setResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.se.torrentkatten.fourtyk.api.GameDTO.prototype.hasResult = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.se.torrentkatten.fourtyk.api.GameHandle.prototype.toObject = function(opt_includeInstance) {
  return proto.se.torrentkatten.fourtyk.api.GameHandle.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.se.torrentkatten.fourtyk.api.GameHandle} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.se.torrentkatten.fourtyk.api.GameHandle.toObject = function(includeInstance, msg) {
  var f, obj = {
    uuid: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.se.torrentkatten.fourtyk.api.GameHandle}
 */
proto.se.torrentkatten.fourtyk.api.GameHandle.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.se.torrentkatten.fourtyk.api.GameHandle;
  return proto.se.torrentkatten.fourtyk.api.GameHandle.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.se.torrentkatten.fourtyk.api.GameHandle} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.se.torrentkatten.fourtyk.api.GameHandle}
 */
proto.se.torrentkatten.fourtyk.api.GameHandle.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUuid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.se.torrentkatten.fourtyk.api.GameHandle.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.se.torrentkatten.fourtyk.api.GameHandle.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.se.torrentkatten.fourtyk.api.GameHandle} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.se.torrentkatten.fourtyk.api.GameHandle.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string uuid = 1;
 * @return {string}
 */
proto.se.torrentkatten.fourtyk.api.GameHandle.prototype.getUuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.se.torrentkatten.fourtyk.api.GameHandle} returns this
 */
proto.se.torrentkatten.fourtyk.api.GameHandle.prototype.setUuid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.se.torrentkatten.fourtyk.api.GameResultDTO.prototype.toObject = function(opt_includeInstance) {
  return proto.se.torrentkatten.fourtyk.api.GameResultDTO.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.se.torrentkatten.fourtyk.api.GameResultDTO} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.se.torrentkatten.fourtyk.api.GameResultDTO.toObject = function(includeInstance, msg) {
  var f, obj = {
    attackerScore: jspb.Message.getFieldWithDefault(msg, 1, 0),
    defenderScore: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.se.torrentkatten.fourtyk.api.GameResultDTO}
 */
proto.se.torrentkatten.fourtyk.api.GameResultDTO.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.se.torrentkatten.fourtyk.api.GameResultDTO;
  return proto.se.torrentkatten.fourtyk.api.GameResultDTO.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.se.torrentkatten.fourtyk.api.GameResultDTO} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.se.torrentkatten.fourtyk.api.GameResultDTO}
 */
proto.se.torrentkatten.fourtyk.api.GameResultDTO.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAttackerScore(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDefenderScore(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.se.torrentkatten.fourtyk.api.GameResultDTO.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.se.torrentkatten.fourtyk.api.GameResultDTO.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.se.torrentkatten.fourtyk.api.GameResultDTO} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.se.torrentkatten.fourtyk.api.GameResultDTO.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAttackerScore();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getDefenderScore();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional int32 attacker_score = 1;
 * @return {number}
 */
proto.se.torrentkatten.fourtyk.api.GameResultDTO.prototype.getAttackerScore = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.se.torrentkatten.fourtyk.api.GameResultDTO} returns this
 */
proto.se.torrentkatten.fourtyk.api.GameResultDTO.prototype.setAttackerScore = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 defender_score = 2;
 * @return {number}
 */
proto.se.torrentkatten.fourtyk.api.GameResultDTO.prototype.getDefenderScore = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.se.torrentkatten.fourtyk.api.GameResultDTO} returns this
 */
proto.se.torrentkatten.fourtyk.api.GameResultDTO.prototype.setDefenderScore = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


goog.object.extend(exports, proto.se.torrentkatten.fourtyk.api);
